services:
  db:
    image: postgres:15
    container_name: mycelium_postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:
