/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPostIdIndexRouteImport } from './routes/$blogPostId/index'
import { Route as BlogPostIdEditRouteImport } from './routes/$blogPostId/edit'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdIndexRoute = BlogPostIdIndexRouteImport.update({
  id: '/$blogPostId/',
  path: '/$blogPostId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdEditRoute = BlogPostIdEditRouteImport.update({
  id: '/$blogPostId/edit',
  path: '/$blogPostId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/$blogPostId/edit': typeof BlogPostIdEditRoute
  '/$blogPostId': typeof BlogPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/$blogPostId/edit': typeof BlogPostIdEditRoute
  '/$blogPostId': typeof BlogPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/$blogPostId/edit': typeof BlogPostIdEditRoute
  '/$blogPostId/': typeof BlogPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/$blogPostId/edit' | '/$blogPostId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/$blogPostId/edit' | '/$blogPostId'
  id: '__root__' | '/' | '/create' | '/$blogPostId/edit' | '/$blogPostId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  BlogPostIdEditRoute: typeof BlogPostIdEditRoute
  BlogPostIdIndexRoute: typeof BlogPostIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$blogPostId/': {
      id: '/$blogPostId/'
      path: '/$blogPostId'
      fullPath: '/$blogPostId'
      preLoaderRoute: typeof BlogPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$blogPostId/edit': {
      id: '/$blogPostId/edit'
      path: '/$blogPostId/edit'
      fullPath: '/$blogPostId/edit'
      preLoaderRoute: typeof BlogPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  BlogPostIdEditRoute: BlogPostIdEditRoute,
  BlogPostIdIndexRoute: BlogPostIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
